# Generated by Django 4.2.20 on 2025-05-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalamGazTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=100, verbose_name="Référence"),
                ),
                (
                    "date_export",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'export"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "SalamGaz Tab",
                "verbose_name_plural": "SalamGaz Tabs",
            },
        ),
    ]
