# Generated by Django 4.2.20 on 2025-05-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0014_synclog_syncstate_is_syncing"),
        ("export", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalamGazTabLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(max_length=100, verbose_name="Client")),
                (
                    "depositaire",
                    models.CharField(max_length=100, verbose_name="Dépositaire"),
                ),
                (
                    "marque_bouteille",
                    models.CharField(max_length=100, verbose_name="Marque Bouteille"),
                ),
                (
                    "qte_bd_3kg",
                    models.PositiveIntegerField(default=0, verbose_name="Qté Bd 3KG"),
                ),
                (
                    "qte_bd_6kg",
                    models.PositiveIntegerField(default=0, verbose_name="Qté Bd 6KG"),
                ),
                (
                    "qte_bd_12kg",
                    models.PositiveIntegerField(default=0, verbose_name="Qté Bd 12KG"),
                ),
                (
                    "tonnage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tonnage (kg)",
                    ),
                ),
                ("societe", models.CharField(max_length=100, verbose_name="Société")),
                (
                    "centre_emplisseur",
                    models.CharField(max_length=100, verbose_name="Centre Emplisseur"),
                ),
                (
                    "mt_bl",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="MT BL"
                    ),
                ),
                (
                    "mt_vers_virt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="MT VERS/VIRT",
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Ecart"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observation"),
                ),
                (
                    "export",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="export.salamgaztab",
                    ),
                ),
                (
                    "source_bcs",
                    models.ManyToManyField(
                        blank=True,
                        to="scrap_sga.scrapdimagazbc",
                        verbose_name="BC(s) source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne SalamGaz Tab",
                "verbose_name_plural": "Lignes SalamGaz Tab",
            },
        ),
    ]
