# Generated by Django 4.2.20 on 2025-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0014_synclog_syncstate_is_syncing"),
        ("export", "0002_salamgaztabligne"),
    ]

    operations = [
        migrations.AddField(
            model_name="salamgaztab",
            name="date_debut",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure de début pour la génération automatique des lignes.",
                null=True,
                verbose_name="Date début période",
            ),
        ),
        migrations.AddField(
            model_name="salamgaztab",
            name="date_fin",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure de fin pour la génération automatique des lignes.",
                null=True,
                verbose_name="Date fin période",
            ),
        ),
        migrations.AlterField(
            model_name="salamgaztabligne",
            name="source_bcs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optionnel. Pour les lignes générées automatiquement\u202f: liste des BC à l'origine de cette ligne. Pour les ajouts manuels, peut être laissé vide.",
                to="scrap_sga.scrapdimagazbc",
                verbose_name="BC(s) source",
            ),
        ),
    ]
