# Generated by Django 4.2.20 on 2025-05-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("export", "0003_salamgaztab_date_debut_salamgaztab_date_fin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salamgaztabligne",
            name="client",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Client"
            ),
        ),
    ]
