# Generated by Django 4.2.20 on 2025-05-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("export", "0004_alter_salamgaztabligne_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="salamgaztabligne",
            name="prix_12kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Prix 12KG",
            ),
        ),
        migrations.AddField(
            model_name="salamgaztabligne",
            name="prix_3kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Prix 3KG",
            ),
        ),
        migrations.AddField(
            model_name="salamgaztabligne",
            name="prix_6kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Prix 6KG",
            ),
        ),
    ]
