# Generated by Django 4.2.20 on 2025-05-01 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("export", "0003_alter_salamgaztabligne_depositaire"),
        (
            "export",
            "0005_salamgaztabligne_prix_12kg_salamgaztabligne_prix_3kg_and_more",
        ),
    ]

    operations = []
