# Generated by Django 4.2.20 on 2025-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0017_alter_scrappingconsole_scrap_type"),
        ("export", "0006_merge_20250501_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salamgaztabligne",
            name="prix_12kg",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Prix 12KG"
            ),
        ),
        migrations.AlterField(
            model_name="salamgaztabligne",
            name="prix_3kg",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Prix 3KG"
            ),
        ),
        migrations.AlterField(
            model_name="salamgaztabligne",
            name="prix_6kg",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Prix 6KG"
            ),
        ),
        migrations.AlterField(
            model_name="salamgaztabligne",
            name="source_bcs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optionnel. Pour les lignes générées automatiquement : liste des BC à l'origine de cette ligne. Pour les ajouts manuels, peut être laissé vide.",
                to="scrap_sga.scrapdimagazbc",
                verbose_name="BC(s) source",
            ),
        ),
    ]
