# Generated by Django 4.2.20 on 2025-05-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("export", "0008_salamgaztab_inclure_tous_depositaires"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salamgaztab",
            name="inclure_tous_depositaires",
        ),
        migrations.AlterField(
            model_name="salamgaztab",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Référence"
            ),
        ),
    ]
