# Generated by Django 4.2.20 on 2025-04-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapDimagazBC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("depositaire_id", models.IntegerField(blank=True, null=True)),
                (
                    "depositaire_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_bc", models.DateTimeField(blank=True, null=True)),
                ("etat", models.CharField(blank=True, max_length=50, null=True)),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("write_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapDimagazBCLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(db_index=True, unique=True)),
                ("product_id", models.IntegerField(blank=True, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("qty", models.FloatField(blank=True, null=True)),
                ("qty_vide", models.FloatField(blank=True, null=True)),
                ("qty_retenue", models.FloatField(blank=True, null=True)),
                ("qty_defect", models.FloatField(blank=True, null=True)),
                ("prix", models.FloatField(blank=True, null=True)),
                ("subtotal", models.FloatField(blank=True, null=True)),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("write_date", models.DateTimeField(blank=True, null=True)),
                (
                    "bc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="scrap_sga.scrapdimagazbc",
                    ),
                ),
            ],
        ),
    ]
