# Generated by Django 4.2.20 on 2025-04-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("centre_ids", models.JSONField(blank=True, null=True)),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("write_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapFournisseurCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("write_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
