# Generated by Django 4.2.20 on 2025-04-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0002_scrapfournisseur_scrapfournisseurcentre"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapfournisseurcentre",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="centres",
                to="scrap_sga.scrapfournisseur",
            ),
        ),
    ]
