# Generated by Django 4.2.20 on 2025-04-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0003_scrapfournisseurcentre_fournisseur"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("sap_id", models.CharField(max_length=64)),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("write_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
