# Generated by Django 4.2.20 on 2025-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0005_rename_date_bc_scrapdimagazbc_bc_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("product_id", models.IntegerField()),
                (
                    "product_id_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_category", models.IntegerField(blank=True, null=True)),
                (
                    "product_category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("write_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
