# Generated by Django 4.2.20 on 2025-04-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0006_scrapproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrapdimagazbcline",
            name="product_id",
        ),
        migrations.AddField(
            model_name="scrapdimagazbcline",
            name="bc_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scrapdimagazbcline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bc_lines",
                to="scrap_sga.scrapproduct",
            ),
        ),
    ]
