# Generated by Django 4.2.20 on 2025-04-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0007_remove_scrapdimagazbcline_product_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=20)),
                ("changed_by", models.CharField(blank=True, max_length=100, null=True)),
                ("change_time", models.DateTimeField(auto_now_add=True)),
                ("diff", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="sync_script", max_length=50)),
            ],
        ),
    ]
