# Generated by Django 4.2.20 on 2025-04-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0008_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrappingConsole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scrap_type",
                    models.CharField(
                        choices=[
                            ("user", "Utilisateurs"),
                            ("product", "Produits"),
                            ("fournisseur", "Fournisseurs"),
                            ("centre", "Centres"),
                            ("bc", "Business Case"),
                            ("bc_line", "Lignes BC"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="idle", max_length=20)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("result", models.TextField(blank=True)),
                ("auto_schedule", models.BooleanField(default=False)),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True,
                        help_text="Expression cron si auto_schedule",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
