# Generated by Django 4.2.20 on 2025-04-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0010_alter_scrappingconsole_scrap_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapdimagazbc",
            name="version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
