# Generated by Django 4.2.20 on 2025-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0011_alter_scrapdimagazbc_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapfournisseur",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scrapfournisseur",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scrapfournisseur",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scrapfournisseur",
            name="tel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scrapfournisseur",
            name="ville",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
