# Generated by Django 4.2.20 on 2025-04-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0012_scrapfournisseur_adresse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
