# Generated by Django 4.2.20 on 2025-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0013_syncstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_type", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Succès"),
                            ("error", "Erreur"),
                            ("partial", "Partiel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("bc_synced", models.IntegerField(blank=True, null=True)),
                ("line_synced", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="syncstate",
            name="is_syncing",
            field=models.BooleanField(default=False),
        ),
    ]
