# Generated by Django 4.2.20 on 2025-05-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0014_synclog_syncstate_is_syncing"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapuser",
            name="codeclientSG",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Code client SG"
            ),
        ),
    ]
