# Generated by Django 4.2.20 on 2025-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0015_scrapuser_codeclientsg"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlimentationSolde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(unique=True)),
                ("client_odoo_id", models.IntegerField()),
                ("client_nom", models.CharField(max_length=128)),
                ("solde", models.FloatField()),
                ("state", models.CharField(max_length=32)),
                ("date_done", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("avoir", models.CharField(blank=True, max_length=32, null=True)),
                ("reference_no", models.CharField(max_length=32, unique=True)),
                ("date_creation", models.DateTimeField(blank=True, null=True)),
                ("date_refus", models.DateTimeField(blank=True, null=True)),
                ("refus_raisons", models.TextField(blank=True, null=True)),
                ("source", models.CharField(max_length=32)),
                ("created_by", models.CharField(blank=True, max_length=128, null=True)),
                ("display_name", models.CharField(max_length=128)),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("write_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
