# Generated by Django 4.2.20 on 2025-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap_sga", "0016_alimentationsolde"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrappingconsole",
            name="scrap_type",
            field=models.CharField(
                choices=[
                    ("sync_user", "sync_user"),
                    ("sync_products", "sync_products"),
                    ("sync_FounisseursCentres", "sync_FounisseursCentres"),
                    ("sync_BcLinbc", "sync_BcLinbc"),
                    ("sync_AlimentationSolde", "sync_AlimentationSolde"),
                ],
                max_length=40,
            ),
        ),
    ]
