version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend/frontend-dashboard
    volumes:
      - ./frontend/frontend-dashboard:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8000
    command: npm run dev
