# Generated by Django 4.2.20 on 2025-04-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker_url",
                    models.CharField(
                        default="redis://localhost:6379/0",
                        max_length=255,
                        verbose_name="Broker URL",
                    ),
                ),
                (
                    "result_backend",
                    models.CharField(
                        default="redis://localhost:6379/0",
                        max_length=255,
                        verbose_name="Result Backend",
                    ),
                ),
                ("accept_content", models.CharField(default="json", max_length=100)),
                ("task_serializer", models.CharField(default="json", max_length=50)),
                ("result_serializer", models.CharField(default="json", max_length=50)),
                ("timezone", models.CharField(default="Europe/Paris", max_length=50)),
                (
                    "beat_schedule",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Beat Schedule (JSON)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration Celery",
                "verbose_name_plural": "Configurations Celery",
            },
        ),
        migrations.CreateModel(
            name="RedisConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "redis_url",
                    models.CharField(
                        default="redis://localhost:6379/0",
                        max_length=255,
                        verbose_name="Redis URL",
                    ),
                ),
                (
                    "cache_db",
                    models.PositiveIntegerField(default=1, verbose_name="Cache DB"),
                ),
                (
                    "cache_timeout",
                    models.PositiveIntegerField(
                        default=3600, verbose_name="Cache Timeout (s)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration Redis",
                "verbose_name_plural": "Configurations Redis",
            },
        ),
    ]
