# Generated by Django 4.2.20 on 2025-04-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_config", "0002_celeryconfig_redisconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancedConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_flags",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Feature flags (toggles)"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Mode maintenance"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètres avancés (technique)",
                "verbose_name_plural": "Paramètres avancés (technique)",
            },
        ),
        migrations.CreateModel(
            name="BrandingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="BRASG Dashboard",
                        max_length=100,
                        verbose_name="Titre du site",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="URL du logo"
                    ),
                ),
                (
                    "support_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contact support"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètres d'affichage/branding",
                "verbose_name_plural": "Paramètres d'affichage/branding",
            },
        ),
        migrations.CreateModel(
            name="FunctionalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delai_relance_inactif",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Délai relance inactif (jours)"
                    ),
                ),
                (
                    "delai_relance_app_non_installee",
                    models.PositiveIntegerField(
                        default=3,
                        verbose_name="Délai relance app non installée (jours)",
                    ),
                ),
                (
                    "dashboard_nb_jours_affichage",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Nb jours affichés dashboard"
                    ),
                ),
                (
                    "dashboard_commentaires_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Tags commentaires dashboard",
                    ),
                ),
                (
                    "export_max_rows",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Nb max lignes export"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètres fonctionnels/metier",
                "verbose_name_plural": "Paramètres fonctionnels/metier",
            },
        ),
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_url", models.URLField(max_length=255, verbose_name="URL Odoo")),
                (
                    "odoo_db",
                    models.CharField(max_length=100, verbose_name="Nom base Odoo"),
                ),
                (
                    "odoo_user",
                    models.CharField(max_length=100, verbose_name="Utilisateur Odoo"),
                ),
                (
                    "odoo_password",
                    models.CharField(max_length=100, verbose_name="Mot de passe Odoo"),
                ),
                (
                    "notif_email_from",
                    models.EmailField(
                        max_length=100, verbose_name="Email d'envoi notifications"
                    ),
                ),
                (
                    "notif_sms_provider",
                    models.CharField(
                        max_length=100, verbose_name="Fournisseur SMS (ou config)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètres techniques (API/Notifications)",
                "verbose_name_plural": "Paramètres techniques (API/Notifications)",
            },
        ),
    ]
