# Generated by Django 5.2 on 2025-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_importfichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_profil',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
