# Generated by Django 5.2 on 2025-04-20 13:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('settings', models.JSONField(default=core.models.default_dashboard_settings)),
            ],
            options={
                'verbose_name': 'Configuration du Dashboard',
                'verbose_name_plural': 'Configurations du Dashboard',
            },
        ),
    ]
