# Generated by Django 5.2 on 2025-04-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dashboardconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        # Convertir les valeurs vides en NULL avant changement de type UUID
        migrations.RunSQL(
            sql="UPDATE core_client SET ville = NULL WHERE ville = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.ville'),
        ),
    ]
