# Generated by Django 4.2.20 on 2025-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_client_region_alter_client_ville"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="segment_client",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="CMD/Jour"
            ),
        ),
    ]
