# Generated by Django 4.2.20 on 2025-04-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_client_region_alter_client_segment_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="importfichier",
            name="target_model",
            field=models.CharField(
                choices=[("clients", "Clients"), ("villes", "Villes")],
                default="clients",
                max_length=20,
            ),
        ),
    ]
