# Generated by Django 4.2.20 on 2025-04-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_importfichier_target_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="telephone2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="telephone3",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
