# Generated by Django 4.2.20 on 2025-04-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_notificationclient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="region",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
