# Generated by Django 4.2.20 on 2025-04-29 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_client_date_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cle", models.CharField(max_length=50)),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("nb_bc", models.PositiveIntegerField(default=0)),
                ("nb_lignes", models.PositiveIntegerField(default=0)),
                ("erreurs", models.TextField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle",
                    models.CharField(
                        choices=[("bclinbc", "BC & Lignes BC")],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("is_syncing", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
