# Generated by Django 4.2.20 on 2025-05-02 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_synclog_syncstate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SyncLog",
        ),
        migrations.DeleteModel(
            name="SyncState",
        ),
    ]
